---
# tasks 02_azure_preparation.yaml file for aks-deployment

#- name: Set subscription
#  shell: |
#    az account set --subscription be6a3ac7-c114-43ef-8bac-292ac721df98

- name: Create POC resource group
  azure_rm_resourcegroup:
    auth_source: "{{ auth_source }}"
    name: "{{ resource_group.name }}"
    location: "{{ region.name }}"
  register: rg_status

- debug:
    msg: "{{ rg_status }}"

- name: Create a virtual network
  azure_rm_virtualnetwork:
    name: "{{ vnet.name }}"
    resource_group: "{{ resource_group.name }}"
    address_prefixes_cidr:
        - "{{ vnet.address_prefixes_cidr }}"
    dns_servers:
        - "{{ vnet.dns }}"
    auth_source: "{{ auth_source }}"
    tags:
        poc: "{{ vnet.tag }}"

- name: Create a subnet
  azure_rm_subnet:
    name: "{{ subnet.name }}"
    virtual_network_name: "{{ vnet.name }}"
    resource_group: "{{ resource_group.name }}"
    address_prefix_cidr: "{{ subnet.address_prefix_cidr }}"
    auth_source: "{{ auth_source }}"



