---
# 03_create_aks_cluster file for aks-deployment
- name: Create a managed Azure Container Services (AKS) instance
  azure_rm_aks:
    name: "{{ aks.name }}"
    location: "{{ region.name }}"
    resource_group: "{{ resource_group.name }}"
    dns_prefix: "{{ aks.dns_prefix }}"
    linux_profile:
      admin_username: "{{ aks.linux_profile.username }}"
      ssh_key: "{{ aks.linux_profile.ssh_key }}"
    service_principal:
      client_id: "{{ aks_sp_client }}"
      client_secret: "{{ aks_sp_password }}"
    agent_pool_profiles:
      - name: "{{ aks.agent_pool_profiles.name }}"
        count: "{{ aks.agent_pool_profiles.count }}"
        vm_size: "{{ aks.agent_pool_profiles.vm_size }}"
    auth_source: "{{ aks.auth_source }}"
    tags:
      poc: "{{ aks.tag }}"
    

    
      