---
# vars file for aks-deployment
auth_source: env

region:
  name: eastus2

resource_group:
  name: "RG-{{ project_name }}-{{ deployment_enviroment }}"

vnet:
  name: "VNET-{{ project_name }}-{{ deployment_enviroment }}"
  address_prefixes_cidr: 172.30.239.0/24
  tag: 
    ENV: "{{ deployment_enviroment }}"

subnet:
  name: SNET-{{ project_name }}-{{ deployment_enviroment }}
  virtual_network_name: "{{ vnet.name }}"
  address_prefix_cidr: 172.30.239.0/24
  id: /subscriptions/b892494a-44a7-437b-a2f7-bc484f521353/resourceGroups/RG-genesis-dev/providers/Microsoft.Network/virtualNetworks/VNET-aks-dev/subnets/SNET-aks-genesis

aks:
  api_profile: "latest"
  name: "aks-{{ project_name }}-{{ deployment_enviroment }}"
  dns_prefix: "{{ project_name }}"
  version: '1.13.5'
  linux_profile:
    username: "{{ project_name }}"
    ssh_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDQLvjVRST6uOhTUa2CVFJQaoGPVOmUepo2gene7Fo13yaiYaBkJ6v3v09D0LIaYnGvmHiuKizfnS7v+MKFhKrt4/Sbx5P0J9PxPyECDy2KmXlohVAWfq54BqHzZLByMwwNWZKybQR2wtxJ6Eyj61SPWBmKLf74VX3strD4ogydDVzeTGlwP0QElKs4mWup1JyGRjpr+fknRgG1LKIUyn/TrEvRH4z5Q39c+WU/633HOpREPIzO04I7nan4vx/XFTa5qPHm6klzNnSJti8RUGM6pO+XkzcdCs1mSN6gtwsoUawgeTtubBKO8x6SN/kLqYjfD7P067rSJXCnEla98SwV vagrant@localhost.localdomain'
  agent_pool_profiles:
    name: "{{ project_name }}"
    count: 2
    vm_size: Standard_D8s_v3
  network_profile:
    network_plugin: kubenet
    dns_service_ip: 10.0.0.10
    service_cidr: 10.0.0.0/16
    pod_cidr: 10.244.0.0/16
    docker_bridge_cidr: 172.17.0.1/16
  virtual_node:
    enabled: no
  tag: 
    ENV: "{{ deployment_enviroment }}"
  addon:
    http_application_routing:
      enabled: no
  namespace: '{{ project_name }}'
  rbac: yes

certificate:
  type: "-x509"
  durantion_days: 365
  length: "rsa:2048"
  keyout: "aks_{{ project_name }}_{{ deployment_enviroment }}.key"
  certout: "aks_{{ project_name }}_{{ deployment_enviroment }}.pem"
  cn: "{{ project_name }}"
  ou: "telefonica.com"
  outputdir: "/tmp"

namespace: '{{ project_name }}'

ingress_controller:
  secret: poc-ingresscontroller-secret

acr:
  name: pocacrtdp
  sku: Standard
  tag: "tdppoc"
  secretname: "pocacr-registry"

mysql:
  name: "pocaksmysql"